/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.main.Session;
import com.lorraine.models.AccountModel;
import com.lorraine.services.AccountService;
import com.lorraine.views.AccountCard;
import com.lorraine.utils.CurrencyFormatter;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import raven.toast.Notifications;

/**
 *
 * @author lorraineb, seany
 */
public class AccountsPanel extends javax.swing.JPanel {
    
    private static final Logger LOGGER = Logger.getLogger(AccountsPanel.class.getName());
    
    private final AccountService accountService = new AccountService();
    
    /**
     * Creates new form AccountsPanel
     */
    public AccountsPanel() {
        initComponents();
        initComponentProperties();
        loadAccounts();
    }
    
    private void initComponentProperties() {
        scrollPane.putClientProperty(FlatClientProperties.STYLE, "border:0,0,0,0;");
        scrollPane.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE,
                "trackArc:999; trackInsets:3,3,3,3; thumbInsets:3,3,3,3;");
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        addButton.putClientProperty(FlatClientProperties.STYLE,
                "arc:10; borderWidth:0; focusWidth:0; innerFocusWidth:0;");

        titleLabel.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        titleLabel.setForeground(new Color(17, 24, 39));

        applySummaryStyle(totalAccountsCard, totalAccountsLabel, totalAccountsValue, new Color(219, 234, 254), new Color(29, 78, 216));
        applySummaryStyle(totalBalanceCard, totalBalanceLabel, totalBalanceValue,  new Color(220, 252, 231), new Color(21, 128, 61));
    }

    private void applySummaryStyle(JPanel card, JLabel label, JLabel value, Color background, Color foreground) {
        card.setBackground(background);
        card.putClientProperty(FlatClientProperties.STYLE, "arc:14;");

        label.setFont(new Font("Segoe UI", Font.BOLD, 11));
        label.setForeground(new Color(foreground.getRed(), foreground.getGreen(), foreground.getBlue(), 180));

        value.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 22));
        value.setForeground(foreground);
    }
    
    private void loadAccounts() {
        cardsContainer.removeAll();

        try {
            List<AccountModel> accounts = accountService.getAccountsByUser(Session.getUserID());

            BigDecimal totalBalance = accounts.stream()
                .map(AccountModel::getBalance)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

            totalAccountsValue.setText(String.valueOf(accounts.size()));
            totalBalanceValue.setText(CurrencyFormatter.format(totalBalance));

            for (AccountModel account : accounts) {
                AccountCard card = new AccountCard(account);
                card.setOnEdit(this::onEditAccount);
                card.setOnDelete(this::onDeleteAccount);
                cardsContainer.add(card);
            }
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Error loading accounts", e);
        }

        cardsContainer.revalidate();
        cardsContainer.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        addButton = new com.lorraine.swing.ButtonAction();
        summaryPanel = new javax.swing.JPanel();
        totalAccountsCard = new javax.swing.JPanel();
        totalAccountsLabel = new javax.swing.JLabel();
        totalAccountsValue = new javax.swing.JLabel();
        totalBalanceCard = new javax.swing.JPanel();
        totalBalanceLabel = new javax.swing.JLabel();
        totalBalanceValue = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        cardsContainer = new com.lorraine.swing.CardsPanel();

        mainContainer.setPreferredSize(new java.awt.Dimension(900, 600));

        headerPanel.setPreferredSize(new java.awt.Dimension(852, 28));

        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        titleLabel.setText("Accounts");

        addButton.setText("Add Account");
        addButton.setToolTipText("");
        addButton.setPreferredSize(new java.awt.Dimension(120, 28));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        summaryPanel.setBackground(new java.awt.Color(0, 255, 0));
        summaryPanel.setPreferredSize(new java.awt.Dimension(852, 80));

        totalAccountsCard.setPreferredSize(new java.awt.Dimension(414, 80));

        totalAccountsLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        totalAccountsLabel.setText("TOTAL ACCOUNTS");

        totalAccountsValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        totalAccountsValue.setText("0");

        javax.swing.GroupLayout totalAccountsCardLayout = new javax.swing.GroupLayout(totalAccountsCard);
        totalAccountsCard.setLayout(totalAccountsCardLayout);
        totalAccountsCardLayout.setHorizontalGroup(
            totalAccountsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalAccountsCardLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(totalAccountsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalAccountsValue)
                    .addComponent(totalAccountsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalAccountsCardLayout.setVerticalGroup(
            totalAccountsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalAccountsCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(totalAccountsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalAccountsValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        totalBalanceCard.setPreferredSize(new java.awt.Dimension(414, 80));

        totalBalanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        totalBalanceLabel.setText("TOTAL BALANCE");

        totalBalanceValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        totalBalanceValue.setText("0");

        javax.swing.GroupLayout totalBalanceCardLayout = new javax.swing.GroupLayout(totalBalanceCard);
        totalBalanceCard.setLayout(totalBalanceCardLayout);
        totalBalanceCardLayout.setHorizontalGroup(
            totalBalanceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBalanceCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(totalBalanceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBalanceValue)
                    .addComponent(totalBalanceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totalBalanceCardLayout.setVerticalGroup(
            totalBalanceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalBalanceCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(totalBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBalanceValue)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addComponent(totalAccountsCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(totalBalanceCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalAccountsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBalanceCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new java.awt.Dimension(852, 360));

        cardsContainer.setBackground(new java.awt.Color(0, 0, 0));
        scrollPane.setViewportView(cardsContainer);

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
//        CategoryForm form = buildForm();
//        showCategoryPopup("Add Category", "Add Category", form, (pc, data) -> {
//            boolean success = categoryService.addCategory(
//                Session.getUserID(), data.getName()
//            );
//            if (success) {
//                pc.closePopup();
//                loadCategories();
//                Notifications.getInstance().show(Notifications.Type.SUCCESS, "Category added successfully.");
//            } else {
//                Notifications.getInstance().show(Notifications.Type.ERROR, "Failed to add category.");
//            }
//        });
    }//GEN-LAST:event_addButtonActionPerformed
    
    private void onEditAccount(AccountModel account) {
        
    }

    private void onDeleteAccount(AccountModel account) {
        boolean success = accountService.deleteAccount(account.getID());
        if (success) {
            loadAccounts();
            Notifications.getInstance().show(Notifications.Type.SUCCESS, "Account deleted.");
        } else {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Failed to delete account.");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.lorraine.swing.ButtonAction addButton;
    private com.lorraine.swing.CardsPanel cardsContainer;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel totalAccountsCard;
    private javax.swing.JLabel totalAccountsLabel;
    private javax.swing.JLabel totalAccountsValue;
    private javax.swing.JPanel totalBalanceCard;
    private javax.swing.JLabel totalBalanceLabel;
    private javax.swing.JLabel totalBalanceValue;
    // End of variables declaration//GEN-END:variables
}
