/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.main.Session;
import com.lorraine.models.AccountModel;
import com.lorraine.models.CategoryModel;
import com.lorraine.models.TransactionModel;
import com.lorraine.models.TransactionType;
import com.lorraine.services.AccountService;
import com.lorraine.services.CategoryService;
import com.lorraine.services.TransactionService;
import com.lorraine.utils.CurrencyFormatter;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;
import raven.datetime.DatePicker;
import raven.popup.GlassPanePopup;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author lorraineb, seany
 */
public class AccountForm extends javax.swing.JPanel {

    
    private static final Logger LOGGER = Logger.getLogger(AccountForm.class.getName());
    
    /**
     * Creates new form addTransactionData
     */
    public AccountForm() {
        init();
    }
    
    private void init() {
        initComponents();
        initComponentProperties();
        CurrencyFormatter.setup(amountField);
    }
    
    private void initComponentProperties() {
        String roundedStyle = "arc:15;borderWidth:0;focusWidth:0;innerFocusWidth:0;";
        
        accountCBX.putClientProperty(FlatClientProperties.STYLE, roundedStyle);
        descriptionField.putClientProperty(FlatClientProperties.STYLE, roundedStyle + "margin:5,10,5,10;");
        
        descriptionField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "e.g. Jollibee Lunch, Netflix Subscription...");
        amountField.putClientProperty(FlatClientProperties.STYLE, roundedStyle + "margin:5,10,5,10;");
    }
    
    public void prefill(TransactionModel t) {
        if (t == null) return;
        
        descriptionField.setText(t.getDescription());
        amountField.setValue(t.getAmount());
        
        for (int i = 0; i < accountCBX.getItemCount(); i++) {
            AccountModel a = (AccountModel) accountCBX.getItemAt(i);
            if (a.getName().equals(t.getAccountName())) {
                accountCBX.setSelectedItem(a);
                break;
            }
        }
    }
    
//    public TransactionModel getData() {
//        
//        try {
//            amountField.commitEdit();
//        } catch (java.text.ParseException e) {
//            LOGGER.log(Level.WARNING, "Invalid amount input", e);
//        }
//        
//        if (!isFormValid()) return null;
//        
//        String description      = descriptionField.getText().trim();
//        BigDecimal amount       = CurrencyFormatter.getValue(amountField);
//        AccountModel account    = (AccountModel) accountCBX.getSelectedItem();
//
//        return new TransactionModel(Session.getUserID(), account.getID(), category.getID(), type, amount, date, description);
//    }
//    
//    private boolean isFormValid() {
//        return typeCBX.getSelectedItem() != null
//            && accountCBX.getSelectedItem() != null
//            && categoryCBX.getSelectedItem() != null
//            && datePicker.getSelectedDate() != null
//            && !descriptionField.getText().trim().isEmpty()
//            && CurrencyFormatter.getValue(amountField).compareTo(BigDecimal.ZERO) > 0;
//    }
//    
//    public JComboBox<AccountModel> getAccountCBX()       { return accountCBX; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransactionFormContainer = new javax.swing.JPanel();
        descriptionField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        accountCBX = new javax.swing.JComboBox<>();
        amountField = new javax.swing.JFormattedTextField();

        descriptionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descriptionLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        descriptionLabel.setText("ACCOUNT NAME");

        amountLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        amountLabel.setText("BALANCE (₱)");

        accountLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        accountLabel.setText("ACCOUNT TYPE");

        accountCBX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout TransactionFormContainerLayout = new javax.swing.GroupLayout(TransactionFormContainer);
        TransactionFormContainer.setLayout(TransactionFormContainerLayout);
        TransactionFormContainerLayout.setHorizontalGroup(
            TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionFormContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(descriptionField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountCBX, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        TransactionFormContainerLayout.setVerticalGroup(
            TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionFormContainerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(accountCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(amountLabel)
                .addGap(0, 0, 0)
                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TransactionFormContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransactionFormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TransactionFormContainer;
    private javax.swing.JComboBox<AccountModel> accountCBX;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JFormattedTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel descriptionLabel;
    // End of variables declaration//GEN-END:variables
}