/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.lorraine.main.MainFrame;
import com.lorraine.swing.ButtonAction;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author seany
 */
public class AuthPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AuthPanel
     */
    public AuthPanel() {
        initComponents();
    }

    private void initButton() {
        
        ButtonAction[] buttons = {
            testButton,
            testButton2
        };
        
        for (ButtonAction button : buttons) {
            
            button.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    System.out.println("cute si sean");
                }
                @Override
                public void mousePressed(MouseEvent e) {
                    
                }
                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthBackground = new javax.swing.JPanel();
        AuthContainer = new javax.swing.JPanel();
        AuthHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginButton = new com.lorraine.swing.Button();
        registerButton = new com.lorraine.swing.Button();
        jLabel1 = new javax.swing.JLabel();
        testButton = new com.lorraine.swing.ButtonAction();
        testButton2 = new com.lorraine.swing.ButtonAction();

        AuthBackground.setBackground(new java.awt.Color(255, 255, 255));
        AuthBackground.setPreferredSize(new java.awt.Dimension(1000, 600));

        AuthContainer.setBackground(new java.awt.Color(255, 255, 255));
        AuthContainer.setPreferredSize(new java.awt.Dimension(400, 400));

        AuthHeader.setBackground(new java.awt.Color(255, 255, 255));
        AuthHeader.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/finance_icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Finance Tracker System");

        javax.swing.GroupLayout AuthHeaderLayout = new javax.swing.GroupLayout(AuthHeader);
        AuthHeader.setLayout(AuthHeaderLayout);
        AuthHeaderLayout.setHorizontalGroup(
            AuthHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AuthHeaderLayout.setVerticalGroup(
            AuthHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthHeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginButton.setBackground(new java.awt.Color(51, 204, 0));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        loginButton.setPreferredSize(new java.awt.Dimension(300, 40));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(51, 51, 51));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Create an Account");
        registerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        registerButton.setPreferredSize(new java.awt.Dimension(300, 40));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Or");

        javax.swing.GroupLayout AuthContainerLayout = new javax.swing.GroupLayout(AuthContainer);
        AuthContainer.setLayout(AuthContainerLayout);
        AuthContainerLayout.setHorizontalGroup(
            AuthContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AuthContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthContainerLayout.createSequentialGroup()
                        .addComponent(AuthHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AuthContainerLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(AuthContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        AuthContainerLayout.setVerticalGroup(
            AuthContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AuthHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );

        testButton.setText("buttonAction1");

        testButton2.setText("buttonAction1");

        javax.swing.GroupLayout AuthBackgroundLayout = new javax.swing.GroupLayout(AuthBackground);
        AuthBackground.setLayout(AuthBackgroundLayout);
        AuthBackgroundLayout.setHorizontalGroup(
            AuthBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthBackgroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AuthBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(AuthContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        AuthBackgroundLayout.setVerticalGroup(
            AuthBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthBackgroundLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(AuthContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(AuthBackgroundLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(AuthBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AuthBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        MainFrame mainForm = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mainForm != null) {
            mainForm.setView(new LoginPanel());
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        MainFrame mainForm = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mainForm != null) {
            mainForm.setView(new RegisterPanel());
        }
    }//GEN-LAST:event_registerButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AuthBackground;
    private javax.swing.JPanel AuthContainer;
    private javax.swing.JPanel AuthHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private com.lorraine.swing.Button loginButton;
    private com.lorraine.swing.Button registerButton;
    private com.lorraine.swing.ButtonAction testButton;
    private com.lorraine.swing.ButtonAction testButton2;
    // End of variables declaration//GEN-END:variables
}
