/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.main.Session;
import com.lorraine.models.CategoryModel;
import java.util.logging.Logger;

/**
 *
 * @author lorraineb, seany
 */
public class CategoryForm extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(CategoryForm.class.getName());
    
    /**
     * Creates new form CategoryForm
     */
    public CategoryForm() {
        init();
    }
    
    private void init() {
        initComponents();
        initComponentProperties();
    }

    private void initComponentProperties() {
        String roundedStyle = "arc:15;borderWidth:0;focusWidth:0;innerFocusWidth:0;";
        
        categoryField.putClientProperty(FlatClientProperties.STYLE, roundedStyle + "margin:5,10,5,10;");
        categoryField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "e.g. Donations, Delivery...");
    }
    
    public void prefill(CategoryModel t) {
        if (t == null) return;
        categoryField.setText(t.getName());
    }
    
    public CategoryModel getData() {
        if (!isFormValid()) return null;
        String description = categoryField.getText().trim();
        return new CategoryModel(Session.getUserID(), description);
    }
    
    private boolean isFormValid() {
        return !categoryField.getText().trim().isEmpty();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransactionFormContainer = new javax.swing.JPanel();
        categoryField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();

        categoryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        categoryLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        categoryLabel.setText("CATEGORY NAME");

        javax.swing.GroupLayout TransactionFormContainerLayout = new javax.swing.GroupLayout(TransactionFormContainer);
        TransactionFormContainer.setLayout(TransactionFormContainerLayout);
        TransactionFormContainerLayout.setHorizontalGroup(
            TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransactionFormContainerLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(categoryField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        TransactionFormContainerLayout.setVerticalGroup(
            TransactionFormContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionFormContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransactionFormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TransactionFormContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TransactionFormContainer;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categoryLabel;
    // End of variables declaration//GEN-END:variables
}