/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.lorraine.main.MainFrame;
import com.lorraine.main.MainPanel;
import com.lorraine.main.Session;
import com.lorraine.services.AuthenticationService;
import com.lorraine.models.LoginResult;
import com.lorraine.models.ValidationResult;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author ihub28
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private static final int MESSAGE_LABEL_HEIGHT = 40;
    private static final int MESSAGE_LABEL_WIDTH = 310;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        messageLabel.setVisible(false);
        emailField.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginBackground = new javax.swing.JPanel();
        LoginContainer = new javax.swing.JPanel();
        LoginHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        emailField = new com.lorraine.swing.TextField();
        passwordField = new com.lorraine.swing.PasswordField();
        signinButton = new com.lorraine.swing.Button();
        messageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new com.lorraine.swing.Button();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        LoginBackground.setBackground(new java.awt.Color(255, 255, 255));
        LoginBackground.setPreferredSize(new java.awt.Dimension(1000, 600));

        LoginContainer.setBackground(new java.awt.Color(255, 255, 255));
        LoginContainer.setPreferredSize(new java.awt.Dimension(400, 400));

        LoginHeader.setBackground(new java.awt.Color(255, 255, 255));
        LoginHeader.setOpaque(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/finance_icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Finance Tracker System");

        javax.swing.GroupLayout LoginHeaderLayout = new javax.swing.GroupLayout(LoginHeader);
        LoginHeader.setLayout(LoginHeaderLayout);
        LoginHeaderLayout.setHorizontalGroup(
            LoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginHeaderLayout.setVerticalGroup(
            LoginHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginHeaderLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        showPasswordCheckBox.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        showPasswordCheckBox.setText("Show Password?");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.setLabelText("Email");

        passwordField.setToolTipText("");
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setLabelText("Password");

        signinButton.setBackground(new java.awt.Color(51, 204, 0));
        signinButton.setText("Sign in");
        signinButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Forgot password?");

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Go back");
        backButton.setToolTipText("");
        backButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginContainerLayout = new javax.swing.GroupLayout(LoginContainer);
        LoginContainer.setLayout(LoginContainerLayout);
        LoginContainerLayout.setHorizontalGroup(
            LoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginContainerLayout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(LoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginContainerLayout.createSequentialGroup()
                                .addComponent(showPasswordCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LoginContainerLayout.setVerticalGroup(
            LoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showPasswordCheckBox)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signinButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LoginBackgroundLayout = new javax.swing.GroupLayout(LoginBackground);
        LoginBackground.setLayout(LoginBackgroundLayout);
        LoginBackgroundLayout.setHorizontalGroup(
            LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginBackgroundLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(LoginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        LoginBackgroundLayout.setVerticalGroup(
            LoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginBackgroundLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(LoginContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadImage(String image) {
        
        ImageIcon imageIcon;
        try {
            switch(image) {
                case "warning" -> { 
                    imageIcon = new ImageIcon(getClass().getResource("/icons/caution.png")); 
                    messageLabel.setForeground(new java.awt.Color(0, 0, 0));
                }
                case "error" -> { 
                    imageIcon = new ImageIcon(getClass().getResource("/icons/error.png"));
                    messageLabel.setForeground(new java.awt.Color(204, 0, 0)); 
                }
                default -> { imageIcon = null;
                    messageLabel.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            
            messageLabel.setIcon(imageIcon);
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, "Could not load icon: " + image, e);
        }
    }
    
    private ValidationResult validateInputs() {
        String email = emailField.getText().trim();
        String password = String.valueOf(passwordField.getPassword());
        
        if (email.isEmpty() && password.isEmpty()) {
            emailField.grabFocus();
            return ValidationResult.failed("Please fill out the missing fields.");
        }
        
        if (email.isEmpty()){
            emailField.grabFocus();
            return ValidationResult.failed("Please fill out the email field.");
        }
        
        if (password.isEmpty()){
            passwordField.grabFocus();
            return ValidationResult.failed("Please fill out the password field.");
        }
        
        return ValidationResult.success();
    }
    
    private void showMessage(String message, String icon) {
//        hideLoading();
        loadImage(icon);
        messageLabel.setText(message);
        messageLabel.setPreferredSize(new Dimension(MESSAGE_LABEL_WIDTH, MESSAGE_LABEL_HEIGHT));
        messageLabel.setVisible(true);
//        resizeLoginContainer();
    }
    
    private void hideMessage() {
//        hideLoading();
        messageLabel.setVisible(false);
        messageLabel.setPreferredSize(new Dimension(MESSAGE_LABEL_WIDTH, 0));
//        resetLoginContainerSize();
    }
    
    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        String email = emailField.getText().trim();
        String password = String.valueOf(passwordField.getPassword());
        
        ValidationResult validateResult = validateInputs();
        
        if (!validateResult.isValid()) {
            showMessage(validateResult.getErrorMessage(), "warning");
            return;
        }
        
        AuthenticationService authService = new AuthenticationService();
        LoginResult result = authService.loginUser(email, password);
        
        if (!result.isSuccess()) {
            showMessage(result.getMessage(), "error");
        } else {
            Session.login(result.getUser());
            MainFrame mainForm = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (mainForm != null) mainForm.setView(new MainPanel());
        }
    }//GEN-LAST:event_signinButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainFrame mainForm = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mainForm != null) {
            mainForm.setView(new AuthPanel());
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if (showPasswordCheckBox.isSelected()) {
            passwordField.setEchoChar((char) 0);
        } else {
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginBackground;
    private javax.swing.JPanel LoginContainer;
    private javax.swing.JPanel LoginHeader;
    private com.lorraine.swing.Button backButton;
    private com.lorraine.swing.TextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel messageLabel;
    private com.lorraine.swing.PasswordField passwordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private com.lorraine.swing.Button signinButton;
    // End of variables declaration//GEN-END:variables
}
