/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.main;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.swing.ButtonAction;
import com.lorraine.test.testAccountsPanel;
import com.lorraine.views.AccountsPanel;
import com.lorraine.views.AuthPanel;
import com.lorraine.views.CategoriesPanel;
import com.lorraine.views.DashboardPanel;
import com.lorraine.views.TransactionsPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author lorraineb, seany
 */
public final class MainPanel extends javax.swing.JPanel {
    
    private ButtonAction activeButton = null; 
    
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        contentPanel.setLayout(new BorderLayout());
        initComponentProperties();
        initNavigationButtons();
//        setActiveButton(DashboardButton);
        setContentView(new DashboardPanel());
    }
    
    private void initComponentProperties() {
        NavigationPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, 
                new Color(210, 210, 210)));
    }
    
    private void initNavigationButtons() {
        ButtonAction[] buttons = {
            DashboardButton,
            TransactionsButton,
            AccountsButton,
            CategoriesButton
        };
        
        for (ButtonAction button : buttons) {
            button.addActionListener(e -> setActiveButton(button));
            
            button.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    applyStyle(button, button == activeButton ? "rgb(30,30,30)" : "rgb(210,210,210)", button == activeButton ? "rgb(255,255,255)" : "rgb(38,38,38)");
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    if (button == activeButton) applyStyle(button, "rgb(0,0,0)", "rgb(255,255,255)");
                    else applyStyle(button, "rgb(240,240,240)", "rgb(38,38,38)");
                }
            });
            applyStyle(button, "rgb(240,240,240)", "rgb(38,38,38)");
        }
        setActiveButton(DashboardButton);
    }
    
    private void setActiveButton(ButtonAction button) {
        if (activeButton != null) applyStyle(activeButton, "rgb(240,240,240)", "rgb(38,38,38)");
        applyStyle(button, "rgb(0,0,0)", "rgb(255,255,255)");
        activeButton = button;

        if (button == DashboardButton) setContentView(new testAccountsPanel());
        else if (button == TransactionsButton) setContentView(new TransactionsPanel());
        else if (button == AccountsButton) setContentView(new AccountsPanel());
        else if (button == CategoriesButton) setContentView(new CategoriesPanel());
    }
    
    private void applyStyle(ButtonAction button, String bg, String fg) {
        button.putClientProperty(FlatClientProperties.STYLE,
                "arc:15; borderWidth:0; focusWidth:0; innerFocusWidth:0; margin:5,20,5,20;"
                + "background:" + bg + "; foreground:" + fg);
    }
    
    public void setContentView(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuContainer = new javax.swing.JPanel();
        NavigationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DashboardButton = new com.lorraine.swing.ButtonAction();
        TransactionsButton = new com.lorraine.swing.ButtonAction();
        CategoriesButton = new com.lorraine.swing.ButtonAction();
        buttonAction1 = new com.lorraine.swing.ButtonAction();
        AccountsButton = new com.lorraine.swing.ButtonAction();
        contentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1020, 600));

        NavigationPanel.setBackground(new java.awt.Color(240, 240, 240));
        NavigationPanel.setPreferredSize(new java.awt.Dimension(120, 600));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 112));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 216, 25));
        jLabel2.setText("PesoTrack");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(40, 40, 40))
        );

        DashboardButton.setBackground(new java.awt.Color(240, 240, 240));
        DashboardButton.setText("Dashboard");
        DashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardButtonActionPerformed(evt);
            }
        });

        TransactionsButton.setBackground(new java.awt.Color(240, 240, 240));
        TransactionsButton.setText("Transactions");
        TransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsButtonActionPerformed(evt);
            }
        });

        CategoriesButton.setBackground(new java.awt.Color(240, 240, 240));
        CategoriesButton.setText("Categories");
        CategoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesButtonActionPerformed(evt);
            }
        });

        buttonAction1.setText("Logout");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });

        AccountsButton.setText("Accounts");
        AccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationPanelLayout = new javax.swing.GroupLayout(NavigationPanel);
        NavigationPanel.setLayout(NavigationPanelLayout);
        NavigationPanelLayout.setHorizontalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TransactionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CategoriesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAction1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccountsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigationPanelLayout.setVerticalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CategoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(900, 0));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuContainerLayout = new javax.swing.GroupLayout(MenuContainer);
        MenuContainer.setLayout(MenuContainerLayout);
        MenuContainerLayout.setHorizontalGroup(
            MenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuContainerLayout.createSequentialGroup()
                .addComponent(NavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        MenuContainerLayout.setVerticalGroup(
            MenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(NavigationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MenuContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed
//        setContentView(new DashboardPanel());
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void TransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsButtonActionPerformed
//        setContentView(new TransactionsPanel());
    }//GEN-LAST:event_TransactionsButtonActionPerformed

    private void CategoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesButtonActionPerformed
//        setContentView(new testCategoriesPanel());
    }//GEN-LAST:event_CategoriesButtonActionPerformed

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        Session.logout();
        MainFrame mainForm = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mainForm != null) {
            mainForm.setView(new AuthPanel());
        }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void AccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.lorraine.swing.ButtonAction AccountsButton;
    private com.lorraine.swing.ButtonAction CategoriesButton;
    private com.lorraine.swing.ButtonAction DashboardButton;
    private javax.swing.JPanel MenuContainer;
    private javax.swing.JPanel NavigationPanel;
    private com.lorraine.swing.ButtonAction TransactionsButton;
    private com.lorraine.swing.ButtonAction buttonAction1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
